apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prod-deployment-nginx
  name: prod-deployment-nginx
  namespace: prod-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod-deployment-nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: prod-deployment-nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        resources: {}

