apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2022-12-09T09:48:32Z"
  generation: 1
  labels:
    app: prod-deployment
  name: prod-deployment
  namespace: prod-cluster
  resourceVersion: "14748"
  uid: 16052355-5a33-4045-ae2b-c66607591b9d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: prod-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prod-deployment
    spec:
      containers:
      - image: python:3.8-slim-bullseye
        imagePullPolicy: IfNotPresent
        name: python
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
