apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-cluster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/slayer321/argocd-test.git
    targetRevision: main
    path: prod-cluster/
  destination:
    server: https://kubernetes.default.svc
    namespace: prod-cluster
  syncPolicy:
    automated: {}
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - CreateNamespace=true