apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: first-test-app-nginx
  name: first-test-app-nginx
  namespace: first-test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: first-test-app-nginx
  template:
    metadata:
      labels:
        app: first-test-app-nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
